# This is a basic workflow that is manually triggered

name: Update How to from wiki

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: Update wiki submodule
      run: |
        set -x
        cd docs/wiki
        git submodule update --init --recursive
        cd ../..
        git submodule update --remote --merge
        #git add docs
        git config --global user.email "crramirez@gmail.com"
        git config --global user.name "Carlos Rafael Ramirez"
        git commit -am "Update how-to page"
        git push
